import { Alert, Platform } from 'react-native';
import Share from 'react-native-share';
import * as RNHTMLtoPDF from 'react-native-html-to-pdf';
import RNFS from 'react-native-fs';

export const useExport = () => {

  const shareImage = async (base64Data: string) => {
    try {
      // Clean base64 string if it already contains the prefix
      const cleanBase64 = base64Data.includes('base64,') 
        ? base64Data.split('base64,')[1] 
        : base64Data;

      const filename = `Qivio_Export_${Date.now()}.png`;
      const path = `${RNFS.CachesDirectoryPath}/${filename}`;
      
      await RNFS.writeFile(path, cleanBase64, 'base64');
      
      const url = Platform.OS === 'android' ? `file://${path}` : path;
      
      await Share.open({
        url,
        title: 'Share QR Code',
        message: 'Here is my QR Code created with Qivio!',
      });
      return true;
    } catch (error: any) {
      if (error.message !== 'User did not share') {
        console.error('Error sharing image:', error);
        Alert.alert('Export Error', 'Could not share the image.');
      }
      return false;
    }
  };

  const exportAsPDF = async (base64Data: string, title: string = 'QR Code', action: 'share' | 'save' = 'share') => {
    try {
      const cleanBase64 = base64Data.includes('base64,') 
        ? base64Data.split('base64,')[1] 
        : base64Data;

      const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica', sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #fff; }
              h1 { color: #333; margin-bottom: 20px; }
              img { width: 300px; height: auto; border-radius: 10px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
              .footer { margin-top: 40px; color: #888; font-size: 12px; }
            </style>
          </head>
          <body>
            <h1>${title}</h1>
            <img src="data:image/png;base64,${cleanBase64}" alt="QR Code" />
            <div class="footer">Generated by Qivio App</div>
          </body>
        </html>
      `;

      let options = {
        html: htmlContent,
        fileName: `Qivio_${title.replace(/\s+/g, '_')}_${Date.now()}`,
        base64: true,
      };

      let file = await RNHTMLtoPDF.generatePDF(options);
      
      if (action === 'save') {
        const filename = `${options.fileName}.pdf`;
        const destPath = Platform.OS === 'android' 
          ? `${RNFS.DownloadDirectoryPath}/${filename}` 
          : `${RNFS.DocumentDirectoryPath}/${filename}`;
          
        try {
          if (file.base64) {
            await RNFS.writeFile(destPath, file.base64, 'base64');
          } else if (file.filePath) {
            await RNFS.copyFile(file.filePath, destPath);
          }
          
          if (Platform.OS === 'android') {
            try {
              await RNFS.scanFile(destPath);
            } catch {
              // scanning file isn't critical, ignore
            }
          }
          
          Alert.alert('Success', `PDF saved to ${Platform.OS === 'android' ? 'Downloads' : 'Documents'}.`);
          return true;
        } catch {
          Alert.alert('Error', 'Could not save PDF. Check storage permissions.');
          return false;
        }
      }

      if (file.base64) {
        const filename = `${options.fileName}.pdf`;
        const path = `${RNFS.CachesDirectoryPath}/${filename}`;
        
        await RNFS.writeFile(path, file.base64, 'base64');
        const url = Platform.OS === 'android' ? `file://${path}` : path;

        await Share.open({
          url,
          title: 'Share PDF QR Code',
        });
        return true;
      } else if (file.filePath) {
        // Fallback if base64 isn't returned
        const url = Platform.OS === 'android' ? `file://${file.filePath}` : file.filePath;
        await Share.open({
          url,
          title: 'Share PDF QR Code',
        });
        return true;
      }
      return false;
    } catch (error: any) {
      if (error.message !== 'User did not share') {
        console.error('Error exporting PDF:', error);
        Alert.alert('PDF Export Error', 'Could not generate PDF. Check if you granted storage permissions.');
      }
      return false;
    }
  };

  return {
    shareImage,
    exportAsPDF,
  };
};

